# -*- coding: utf-8 -*-
"""Decision Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PPT4zT-tNTFafzh6obRpdQ7Rn5LBcozq
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
from sklearn.preprocessing import LabelEncoder

car = pd.read_csv("/content/car_evaluation.csv")
car

car.head()

len(car)

col_names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']


car.columns = col_names

col_names

car.head()

pip install category_encoders

car

x = car.drop('class', axis=1)
y = car['class']

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.33,random_state=42)

import category_encoders as ce
encoder = ce.OrdinalEncoder(cols=['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety'])


x_train = encoder.fit_transform(x_train)

x_test = encoder.transform(x_test)

x_train.head()

clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=20, random_state=0)
clf_gini.fit(x_train, y_train)

y_pred = clf_gini.predict(x_test)
from sklearn.metrics import accuracy_score
print('Model accuracy score with criterion gini index: {0:0.4f}'. format(accuracy_score(y_test, y_pred)*100))