# -*- coding: utf-8 -*-
"""RandomForest-Regressor2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TZUU7HeHcRIrMhkgyUpZG3ojFHdK3_Pz
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import r2_score

df = pd.read_csv('/content/gld_price_data.csv')
df

len(df)

#Automatic train
x = df.drop(['Date','EUR/USD'],axis=1)
y = df['EUR/USD']

"""Manual train x and y if needed or not because Automatic train exist,so use any one training method."""

#Manual train
x.iloc[:50,:]

#Manual train
y.iloc[:50]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

rf = RandomForestRegressor(n_estimators=10,random_state=42)
rf.fit(x_train,y_train)

y_pred = rf.predict(x_test)
print(mae(y_pred,y_test),mse(y_pred,y_test),r2_score(y_pred,y_test))